version: 2
updates:
  - package-ecosystem: npm
    directory: /sdk-quickstart
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
  - package-ecosystem: npm
    directory: /adk-hello-agent
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
